### ISSUE TITLE
Can you make a Clojure to Golang compiler?

### ISSUE THREAD

**Issue by Immortalin** [jcla1/gisp#4]
Hi, can you make a Clojure to Golang compiler? The JVM is really slow, a compiled Clojure would be really nice! Thanks in advance!

**Comment by jcla1** [comment]
Hey there
First off, I doubt that writing something _like_ gisp for clojure, wouldn't speed up the execution at all. For one, [the JVM is faster than Go](http://benchmarksgame.alioth.debian.org/u32q/go.php) and second having an object system in Go, like the one in clojure, would almost definitely be a nightmare to manage. Even with gisp's (very) limited abilities, the _type system_ (if you could call it that) is absolutely hideous...
Also, I've no time ATM to work any further on gisp, let alone another (similar) project.
But in case you take up anything in this direction, let me know, I'd be very interested!
